site_name: Searchlab
site_author: Michael Christen
site_description: "Search as a service with YaCy Searchlab: Web Crawling and Data Science Apps for Web Content"
site_url: "https://searchlab.eu"
repo_url: "https://github.com/yacy/searchlab.git"

theme:
    name: null
    custom_dir: 'cinder-superhero'

nav:
  - Home: index.md
  - Access:
    - About the Searchlab: access/about.md
    - Searchlab Architecture: access/architecture.md
    - Download and install Searchlab and YaCy Grid: access/download.md
    - Who made Searchlab - Impressum: access/imprint.md
  - Apps:
    - Data Studio: apps/data_studio.md
    - App Development: apps/app_development.md
    - Search: apps/search.md
  - Production:
    - Crawler: production/crawler.md
    - Network Scanner: production/network_scanner.md
    - Index Import/Export: production/import_export.md
    - Data Warehouse: production/data.md
  - Monitoring:
    - System: monitoring/system.md
    - Crawler: monitoring/crawler.md
    - Indexing: monitoring/indexing.md
  - Admin:
    - Index: admin/search_index.md
    - Crawler: admin/crawler.md

markdown_extensions:
  - admonition
  - attr_list
