site_name: Searchlab
site_author: Michael Christen
site_description: "YaCy Searchlab"
site_url: "https://searchlab.eu"
repo_url: "https://github.com/yacy/searchlab.git"

theme:
    name: null
    custom_dir: 'cinder-superhero'

nav:
  - Home: index.md
  - Software:
    - About the Searchlab: software/about.md
    - Architecture: software/architecture.md
    - Download and install Searchlab and YaCy Grid: software/download.md
    - Imprint/Impressum: software/imprint.md
  - Applications:
    - Search: apps/search.md
    - Data Studio Apps: apps/data_studio.md
    - Search Integration: apps/integration.md
  - Production:
    - Crawler: production/crawler.md
    - Network Scanner: production/network_scanner.md
    - Index Import/Export: production/import_export.md
    - Data Warehouse: production/data.md
  - Monitoring:
    - System: monitoring/system.md
    - Crawler: monitoring/crawler.md
    - Indexing: monitoring/indexing.md
  - Administration:
    - Index: admin/search_index.md
    - Crawler: admin/crawler.md

markdown_extensions:
  - admonition
  - attr_list
