name: CI Script to build on self-hosted server

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean shadowDistTar

